### ISSUE TITLE
特色图像问题

### ISSUE THREAD

**Issue by rankment** [Licoy/wordpress-theme-puock#177]
- 主题版本号：2.6.1
- WordPress版本：6.0.2
- PHP版本：[选填] 7.4
- 问题阐述：

如果post 没有指定特色图像，并且文章第一张图是类似下面的动图，网站首页的缩略图会只显示占位符，可能是缩略图组件对动图处理问题

![webp格式动图](https://rankment.com/wp-content/uploads/2022/09/20220910_math.webp)

https://rankment.com/wp-content/uploads/2022/09/20220910_math.webp

**Comment by rankment** [comment]
更换php8.0/8.1 无法登录，提示：

```txt
Fatal error: Uncaught TypeError: rand(): Argument #2 ($max) must be of type int, float given in /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php:56 Stack trace: #0 /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php(56): rand() #1 /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Theme/UpdateChecker.php(77): Puc_v4p11_Scheduler->__construct() #2 /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/UpdateChecker.php(91): Puc_v4p11_Theme_UpdateChecker->createScheduler() #3 /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Theme/UpdateChecker.php(22): Puc_v4p11_UpdateChecker->__construct() #4 /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Factory.php(121): Puc_v4p11_Theme_UpdateChecker->__construct() #5 /wp-content/themes/wordpress-theme-puock-2.6.1/functions.php(521): Puc_v4p11_Factory::buildUpdateChecker() #6 /wp-content/themes/wordpress-theme-puock-2.6.1/functions.php(532): pk_update() #7 /wp-settings.php(566): include('...') #8 /wp-config.php(97): require_once('...') #9 /wp-load.php(50): require_once('...') #10 /wp-admin/admin.php(34): require_once('...') #11 /wp-admin/index.php(10): require_once('...') #12 {main} thrown in /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php on line 56

Warning: Trying to access array offset on value of type bool in /wp-includes/class-wp-recovery-mode-email-service.php on line 371

Warning: Trying to access array offset on value of type bool in /wp-includes/class-wp-recovery-mode-email-service.php on line 372
```

**Comment by rankment** [comment]
切换 php7.4 可以登录，有告警信息：

```txt
Warning: rand() expects parameter 2 to be int, float given in /wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php on line 56
```

**Comment by rankment** [comment]
登录后切换到8.0 无法编辑帖子，提示：

```txt
Fatal error: Uncaught TypeError: rand(): Argument #2 ($max) must be of type int, float given in/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php:56 Stack trace: #0/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php(56): rand() #1/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Theme/UpdateChecker.php(77): Puc_v4p11_Scheduler->__construct() #2/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/UpdateChecker.php(91): Puc_v4p11_Theme_UpdateChecker->createScheduler() #3/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Theme/UpdateChecker.php(22): Puc_v4p11_UpdateChecker->__construct() #4/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Factory.php(121): Puc_v4p11_Theme_UpdateChecker->__construct() #5/wp-content/themes/wordpress-theme-puock-2.6.1/functions.php(521): Puc_v4p11_Factory::buildUpdateChecker() #6/wp-content/themes/wordpress-theme-puock-2.6.1/functions.php(532): pk_update() #7/wp-settings.php(566): include('...') #8/wp-config.php(97): require_once('...') #9/wp-load.php(50): require_once('...') #10/wp-admin/admin.php(34): require_once('...') #11/wp-admin/post.php(12): require_once('...') #12 {main} thrown in/wp-content/themes/wordpress-theme-puock-2.6.1/update-checker/Puc/v4p11/Scheduler.php on line 56
```

**Comment by rankment** [comment]
> * 主题版本号：2.6.1
> * WordPress版本：6.0.2
> * PHP版本：[选填] 7.4
> * 问题阐述：
> 
> 如果post 没有指定特色图像，并且文章第一张图是类似下面的动图，网站首页的缩略图会只显示占位符，可能是缩略图组件对动图处理问题
> 
> ![webp格式动图](https://camo.githubusercontent.com/c3b4ffc60444179a5e82e28b7a507ffd95e61e1abfe71865ff0eeebc5b9a09fc/68747470733a2f2f72616e6b6d656e742e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032322f30392f32303232303931305f6d6174682e77656270)
> 
> https://rankment.com/wp-content/uploads/2022/09/20220910_math.webp

可以考虑先做判断再处理吗？

**Comment by rankment** [comment]
> @rankment https://rankment.com/wp-content/themes/wordpress-theme-puock-2.6.1/timthumb.php?w=280&h=180&a=&zc=1&src=https://rankment.com/wp-content/uploads/2022/09/20220910_math.webp
> 
> `Fatal error: gd-webp cannot allocate temporary buffer`
> 
> 将你的PHP版本更改为8.0+试试

可以考虑先对图像类型做判断在做图像处理？

**Comment by Licoy** [comment]
我测试为PHP8也没有报出你的上述错误信息

**Comment by rankment** [comment]
可以考虑关闭该问题，太小众了 :)
